// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDII8dkIBTNznjUKtSHCb6D8rAhI7tflHU',
    appId: '1:489024090445:web:b6205d1f0f7346e01d8704',
    messagingSenderId: '489024090445',
    projectId: 'todoapp-e1fce',
    authDomain: 'todoapp-e1fce.firebaseapp.com',
    storageBucket: 'todoapp-e1fce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxesCuasDh6kX39iMjjCDh_LFz11JWEgs',
    appId: '1:489024090445:android:85dc226bb614ad0f1d8704',
    messagingSenderId: '489024090445',
    projectId: 'todoapp-e1fce',
    storageBucket: 'todoapp-e1fce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAagyvDwZBL_CtV6KG9x9xa2qM6_TT3rVQ',
    appId: '1:489024090445:ios:43afefbefa3878671d8704',
    messagingSenderId: '489024090445',
    projectId: 'todoapp-e1fce',
    storageBucket: 'todoapp-e1fce.appspot.com',
    iosClientId: '489024090445-diual7qmt35muupecokp90t1ouqivuca.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAagyvDwZBL_CtV6KG9x9xa2qM6_TT3rVQ',
    appId: '1:489024090445:ios:35df38fe47eb4d061d8704',
    messagingSenderId: '489024090445',
    projectId: 'todoapp-e1fce',
    storageBucket: 'todoapp-e1fce.appspot.com',
    iosClientId: '489024090445-hsem0qg607u90t2f733u7g4mo701mlqp.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp.RunnerTests',
  );
}
